// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Contact Module const
export const FETCH_START = "fetch_start";
export const FETCH_SUCCESS = "fetch_success";
export const FETCH_ERROR = "fetch_error";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

export const GET_CITY = "GET_CITY";
export const GET_DISTRICT = "GET_DISTRICT";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";
export const USER_DATA = "user_data";
export const USER_TOKEN_SET = "user_token_set";
export const CHANGE_PASSWORD = "change_password";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const CHANGE_PROFILE_BLOCK = "CHANGE_PROFILE_BLOCK";
export const COMMON_GET_MENU = "C_G_M";
export const COMMON_GET_MENU_SUCCESS = "C_G_M_S";

export const GET_STICKY = "GET_STICKY";
export const NOTES_UPDATE = "NOTES_UPDATE";
export const FETCH_ALL_NOTES_SUCCESS = "FETCH_ALL_NOTES_SUCCESS";
export const UPDATE_ALL_NOTES_SUCCESS = "UPDATE_ALL_NOTES_SUCCESS";

export const ROLE_ADMIN = "Admin";
//post const
export const POST_GET_LIST = "POST/GET_LIST";
export const POST_GET_LIST_SUCCESS = "POST/GET_LIST_SUCCESS";
export const POST_GET_LIST_ADMIN = "POST/GET_LIST_ADMIN";
export const POST_GET_LIST_SUCCESS_ADMIN = "POST/GET_LIST_SUCCESS_ADMIN";
export const POST_GET_ALL = "POST/GET_ALL";
export const POST_GET_ALL_SUCCESS = "POST/GET_ALL_SUCCESS";
export const POST_CHANGE_STATE = "POST/CHANGE_STATE";
export const POST_CREATE = "POST/CREATE";
export const POST_CREATE_SUCCESS = "POST/CREATE_SUCCESS";
export const POST_UPDATE = "POST/UPDATE";
export const POST_UPDATE_SUCCESS = "POST/UPDATE_SUCCESS";
export const POST_COST_MIN_MAX_SUCCESS = "POST/POST_COST_MIN_MAX_SUCCESS";
export const POST_COST_MIN_MAX = "POST/POST_COST_MIN_MAX";

export const UTILITY_GET_LIST = "UTILITY/GET_LIST";
export const UTILITY_GET_LIST_SUCCESS = "UTILITY/GET_LIST_SUCCESS";
export const UTILITY_CHANGE_STATE = "UTILITY/CHANGE_STATE";

export const POST_TYPE_GET_LIST = "POST_TYPE/GET_LIST";
export const POST_TYPE_GET_LIST_SUCCESS = "POST_TYPE/GET_LIST_SUCCESS";
export const POST_TYPE_CHANGE_STATE = "POST_TYPE/CHANGE_STATE";

export const ROOM_TYPE_GET_LIST = "ROOM_TYPE/GET_LIST";
export const ROOM_TYPE_GET_LIST_SUCCESS = "ROOM_TYPE/GET_LIST_SUCCESS";
export const ROOM_TYPE_CHANGE_STATE = "ROOM_TYPE/CHANGE_STATE";
